### ISSUE TITLE
skipAttributes sets NULL to attributes

### ISSUE THREAD

**Issue by gtux** [phalcon/cphalcon#10249]
Hi, 

  I have an application that is working since 1.2 working fine, I recently I've updated to phalcon 2 and one model begins to have troubles:

  I have an attribute called "created", that is a TIMESTAMP field; also in the initialize method I do specify skip this attribute on insert and update doing this: $this->skipAttributes(array('created')); 

   But it does not work, because on insert sets the attribute created = NULL and MySQL throws an exception.

  For now I workaround setting a some value to created attribute before insert, but, I do not want to change over all models on my application :(

**Comment by Green-Cat** [comment]
Could you please test with 2.0.x?

**Comment by gtux** [comment]
I already have the 2.0.0 version.

**Comment by andresgutierrez** [comment]
@gtux 

```bash
git clone https://github.com/phalcon/cphalcon
cd cphalcon/ext
git checkout 2.0.x
sudo ./install
```

**Comment by gtux** [comment]
I get this:

[ec2-user@ip-172-31-37-28 cphalcon]$ cd ext/
[ec2-user@ip-172-31-37-28 ext]$ git checkout 2.0.x
error: pathspec '2.0.x' did not match any file(s) known to git.

**Comment by sergeyklay** [comment]
@andresgutierrez Why in doc still ? :
```sh
$ cd build/
$ sudo ./install
```

**Comment by Green-Cat** [comment]
@sergeyklay There are two different ways to install phalcon. One is in build and one is in ext.

**Comment by gtux** [comment]
I have cloned the one with git path: git@github.com:phalcon/cphalcon.git, but it does not have the 2.0.x branch, I have to clone the one with https path in order to checkout that branch

**Comment by andresgutierrez** [comment]
@gtux Yes, the branch is there: https://github.com/phalcon/cphalcon/tree/2.0.x

http://stackoverflow.com/questions/9537392/git-fetch-remote-branch

**Comment by sergeyklay** [comment]
@Green-Cat Thanks

**Comment by gtux** [comment]
Well, it seems works well at 2.0.x branch. I must to change to this branch on my host?

**Comment by andresgutierrez** [comment]
2.0.1 is now released

**Comment by vbojan** [comment]
I have the same issue with both 2.0 and 2.0.1 and MySQL 5.6.24:
`created` datetime DEFAULT CURRENT_TIMESTAMP

Phalcon is setting it to NULL, and neither 
I tried both skipAttributes and skipAttributesOnCreate, but Phalcon keeps setting the field to NULL.

@gtux Can you check again if it really works for you?

**Comment by gtux** [comment]
Hi @vbojan just yesterday I got the same issue on 2.0.1 branch in my production environment, and indeed does not work well, the issue persist!

**Comment by andresgutierrez** [comment]
This must be fixed in 2.0.3

**Comment by vbojan** [comment]
Just tested this in 2.0.3 and it still doesn't behave as expected :(

In my case I have a datetime field with DEFAULT CURRENT_TIMESTAMP.
Before it used to insert NULL, but with this change it's now inserting 0000-00-00 00:00:00.

I assume this change won't work fro @gtux either.

**Comment by gtux** [comment]
@vbojan I have already fixed this issue, I had to re create my EC2 instance in order to get right, I never understand why on update my repository don't work

**Comment by vbojan** [comment]
I'm glad you found a solution.
In the meantime I looked into the query being generated and found that it also contains the field marked with skipAttributes. I'd expect it to be completely omitted from the query.

**Comment by andresgutierrez** [comment]
@vbojan skipAttributes are only taken into account in insert/update operations, the idea is make those attributes skipped read-only.

I've added a fix for the issue with CURRENT_TIMESTAMP in the 2.0.x, please compile from ext/.
