### ISSUE TITLE
Database connection can't use persistent option

### ISSUE THREAD

**Issue by ucando** [phalcon/cphalcon#10484]
I use postgresql, and I follow the phalcon's documents to set the persistent option, the code below
```php
$db = new DbAdapter([
    "host" => $config->database->host,
    "port" => $config->database->port,
    "username" => $config->database->username,
    "password" => $config->database->password,
    "dbname" => $config->database->dbname,
    "persistent" => true
  ]);
```
It cause fatal error: SQLSTATE[08006] [7] invalid connection option "persistent". I must change my code like this:
```php
$db = new DbAdapter([
    "host" => $config->database->host,
    "port" => $config->database->port,
    "username" => $config->database->username,
    "password" => $config->database->password,
    "dbname" => $config->database->dbname,
    "options" => [
        PDO::ATTR_PERSISTENT => true
      ]
  ]);
```
and the code can work.

is it a bug? or just the document is wrong?

**Comment by pauliuspetronis** [comment]
I think it's a small bug :)

I think [this](https://github.com/phalcon/cphalcon/blob/master/phalcon/db/adapter/pdo.zep#L138-L142) block has to be before [fetch dnsAttributes](https://github.com/phalcon/cphalcon/blob/master/phalcon/db/adapter/pdo.zep#L125-L131) and `unset descriptor["persistent"]`. Otherwise `persistent` variable is joined to `dsnAttributes` and PostgreSql throw error about it.

**Comment by andresgutierrez** [comment]
This is fixed in the 2.0.3 branch

**Comment by pauliuspetronis** [comment]
I created pull request [https://github.com/phalcon/cphalcon/pull/10489](https://github.com/phalcon/cphalcon/pull/10489). @andresgutierrez - yours fix did not resolve this problem. Because `persistent` is included in to `dnsAttributes`.
