### ISSUE TITLE
Error in read encrypted cookie

### ISSUE THREAD

**Issue by gtux** [phalcon/cphalcon#10487]
Hi,

  I had implemented a remember me feature on my site, now at 2.0.x I have a problem with that. The backtrace is:

```
Info: Parameter 'text' must be a string
#0 [internal function]: Phalcon\Crypt->_cryptUnpadText(false, 'cbc', 32, 0)
#1 [internal function]: Phalcon\Crypt->decrypt('\xBA\thl&\xC8\x01J\xDA\xBCH\x88\x84[\xA8...', NULL)
#2 [internal function]: Phalcon\Crypt->decryptBase64('uglobCbIAUravEi...')
#3 /var/www/vhosts/inngresa.com/apps/library/Gt/Controller/Logeable.php(83): Phalcon\Http\Cookie->getValue()
#4 /var/www/vhosts/inngresa.com/apps/modules/administrador/controllers/IndexController.php(187): Inngresa\Administrador\Controllers\IndexController->handleLogin(Object(Inngresa\Authentication\Adapter\Usuarios))
#5 [internal function]: Inngresa\Administrador\Controllers\IndexController->loginAction()
#6 [internal function]: Phalcon\Dispatcher->dispatch()
#7 /var/www/vhosts/inngresa.com/apps/library/Gt/Mvc/Application.php(107): Phalcon\Mvc\Application->handle()
#8 /var/www/vhosts/inngresa.com/public/index.php(19): Gt\Mvc\Application->run()
#9 {main}
```

On Phalcon\Crypt->_cryptUnpadText the first parameter is false, so it wasn't decrypted, but this feature was working well.

As workaround our users must to erase the cookies and then login.

**Comment by andresgutierrez** [comment]
This is now fixed in the 2.0.3 branch

**Comment by gtux** [comment]
I just update my branch, and the bug persist.

I think it is because the commit fix the send method, but the problem is in decrypt method.

**Comment by dreamsxin** [comment]
Test code
```php
$di = new Phalcon\DI\FactoryDefault();

$key = '#1dj8$=dp?.ak//$';

$di->set('crypt', function() use ($key) {
    $crypt = new Phalcon\Crypt();
    $crypt->setKey($key);
    return $crypt;
});

$cookies = new Phalcon\Http\Response\Cookies();
$cookies->setDI($di);
$cookies->useEncryption(true);

if ($cookies->has('remember-me')) {
	$cookie = $cookies->get('remember-me');
	var_dump($cookie->getValue());
} else {
	$cookies->set('remember-me', 'some value', time() + 15 * 86400);
	$cookies->send();
}

$crypt = new \Phalcon\Crypt();
$text = 'This is a secret text';
$encrypted = $crypt->encrypt($text, $key);
var_dump($key, $crypt->decrypt($encrypted, $key) );
```
