### ISSUE TITLE
[2.0.4] Views Broken using EventsManager in Application

### ISSUE THREAD

**Issue by virgofx** [phalcon/cphalcon#10608]
Setting an events manager to the application breaks views. The page does not display. This is new to 2.0.4.

```php
$application = new Application();
// The following line breaks views from displaying in 2.0.4
$application->setEventsManager($evManager);
$application->setDI($this->di);
echo $application->handle()->getContent();
```

**Comment by andresgutierrez** [comment]
Fixed in the 2.0.x branch

**Comment by broklyngagah** [comment]
@andresgutierrez 
i've pull the new patch and views still not display.

**Comment by andresgutierrez** [comment]
@broklyngagah Did you compile from ext/ in the 2.0.x branch?

**Comment by broklyngagah** [comment]
@andresgutierrez 
apologize. my fault. i pull from wrong tag.
