### ISSUE TITLE
[2.0.5] macros bug

### ISSUE THREAD

**Issue by DestinyMKas** [phalcon/cphalcon#10655]
Hello, i copied code from https://docs.phalconphp.com/en/latest/reference/volt.html#macros example:

```php

{%- macro my_input(name, class="input-text") %}
    {% return text_field(name, 'class': class) %}
{%- endmacro %}

{# Call the macro #}
{{ '<p>' ~ my_input('name') ~ '</p>' }}
{{ '<p>' ~ my_input('name', 'input-text') ~ '</p>' }}

```

And I get an exception: Phalcon\Mvc\View\Exception: Macro 'my_input' does not exist

I checked the code, so I think the problem is Phalcon\Mvc\View\Engine\Volt (volt.zep)
line 40: protected _macros;

_macros cannot be protected, because compiled volt code looks:

```php
$this->_macros['my_input'] = function($__p = null) { ........ }
```

I tried to die in compiled code:

```php
<?php $this->_macros['my_input'] = function($__p = null) { if (isset($__p[0])) { $name = $__p[0]; } else { if (isset($__p["name"])) { $name = $__p["name"]; } else {  throw new \Phalcon\Mvc\View\Exception("Macro 'my_input' was called without parameter: name");  } } if (isset($__p[1])) { $class = $__p[1]; } else { if (isset($__p["class"])) { $class = $__p["class"]; } else { $class = 'input-text'; } }  ?>
    <?php return $this->tag->textField(array($name, 'class' => $class)); ?><?php }; $this->_macros['my_input'] = \Closure::bind($this->_macros['my_input'], $this); ?>

<?php die; ?>
<?php echo '<p>' . $this->callMacro('my_input', array('name')) . '</p>'; ?>
<?php echo '<p>' . $this->callMacro('my_input', array('name', 'input-text')) . '</p>'; ?>
```

and got a lot of errors:

```
Notice: Access to undefined property _macros
Notice: Indirect modification of overloaded property Phalcon\Mvc\View\Engine\Volt::$_macros has no effect
Warning: Closure::bind() expects parameter 1 to be Closure, null given
```

etc...

**Comment by andresgutierrez** [comment]
Can't reproduce this in latest Phalcon 2.0.5

**Comment by DestinyMKas** [comment]
Sorry, my fault.. I have too much extended phalcon & something went wrong..

**Comment by Jurigag** [comment]
@DestinyMKas actually there were a bug for sure, it's now fixed both in 2.0.x and 2.1.x branch

**Comment by akudryav** [comment]
Seems like the problem still exist in 2.1.0 RC 1
script:
``
{%- macro error_messages(message, field, type) %}
    <div>
        <span class="error-type">{{ type }}</span>
        <span class="error-field">{{ field }}</span>
        <span class="error-message">{{ message }}</span>
    </div>
{%- endmacro %}

{{ error_messages('type': 'Invalid', 'message': 'The name is invalid', 'field': 'name') }}
``
Error: Access to undefined property _macros Indirect modification of overloaded property Phalcon\Mvc\View\Engine\Volt::$_macros has no effect

**Comment by sergeyklay** [comment]
Fixed in the `2.1.x` branch.

**Comment by akudryav** [comment]
I have updated my phalcon installation:
```
cd cphalcon
git pull
cd ext
sudo ./install
```
Then restarted php-fpm and nginx, but there is no change. Macro in volt still does not work.
What should I do else?

**Comment by sergeyklay** [comment]
@akudryav

1. https://github.com/phalcon/cphalcon/pull/11883 - as you can see tests passes
2. You have to use th 2.1.x branch
