### ISSUE TITLE
a mistake in your homesite 

### ISSUE THREAD

**Issue by kamitori** [phalcon/cphalcon#10860]
file name is vi.gif
![1](https://cloud.githubusercontent.com/assets/9984084/9576271/6105729a-5000-11e5-8665-e9b1f6909db2.png)

file name is vn.gif
![2](https://cloud.githubusercontent.com/assets/9984084/9576285/7750b924-5000-11e5-968c-42f0ade1b04e.png)

please change vi.gif to vn.gif :laughing:

**Comment by kamitori** [comment]
:laughing::laughing::laughing::laughing::laughing:

**Comment by sergeyklay** [comment]
@andresgutierrez Please enable issues at website https://github.com/phalcon/website and store https://github.com/phalcon/store repos

**Comment by Green-Cat** [comment]
I opened a PR.

**Comment by andresgutierrez** [comment]
Fixed in website repo

**Comment by vanquang9387** [comment]
Not actually fixed. See https://github.com/phalcon/website/pull/301#issuecomment-149522231
