### ISSUE TITLE
[BUG?] After updating Phalcon from 3.0.0 to 3.0.1 or higher raw queries work incorrectly

### ISSUE THREAD

**Issue by yesworld** [phalcon/cphalcon#13081]
In 3.0.0 the code works fine:

```php
$query = "UPDATE \Models\Article SET views = views + 1 WHERE id = :id:";
$article->getModelsManager()->createQuery( $query )->execute(['id' => $article->id]);  //1
$article->getModelsManager()->createQuery( $query )->execute(['id' => $article->id]);  //2
$article->getModelsManager()->createQuery( $query )->execute(['id' => $article->id]);  //3

$art = Article::findFirst( $article->id );
var_dump( $art->views );         // 3
```

In 3.0.1 and higher results are different:
```php
$query = "UPDATE \Models\Article SET views = views + 1 WHERE id = :id:";
$article->getModelsManager()->createQuery( $query )->execute(['id' => $article->id]);  // 1 
$article->getModelsManager()->createQuery( $query )->execute(['id' => $article->id]);  // 1
$article->getModelsManager()->createQuery( $query )->execute(['id' => $article->id]);  // 1

$art = Article::findFirst( $article->id );
var_dump( $art->views );         // 1
```

And another really weird thing is that if I run the mixed code PDO with Phalcon's ORM in 3.0.1 version, the code works fine:
```php
$query = "UPDATE Article SET views = views + 1 WHERE id = ?";
\Phalcon\DI::getDefault()['db']->query($query, [$article->id]);         // 1
\Phalcon\DI::getDefault()['db']->query($query, [$article->id]);         // 2

$query = "UPDATE \Models\Article SET views = views + 1 WHERE id = :id:";
$article->getModelsManager()->createQuery( $query )->execute(['id' => $article->id]);  // 3
$article->getModelsManager()->createQuery( $query )->execute(['id' => $article->id]);  // 4

$art = Article::findFirst( $article->id );
var_dump( $art->views );         // 4
```

I've found the parameter because of which the code gives me different results:
```php
class Article extends \Phalcon\Mvc\Model{
    public $id;
    public $title;
    public $views = 0;

    public function initialize(){
       // $this->useDynamicUpdate(true);  //   <=== Try to uncomment this line
    }

    public function getSource()  {  return 'Article';  }
}
```

Should this parameter work exactly this way in newer versions or not?

### Details
* Phalcon version: 3.0.1 (`php --ri phalcon`)
* PHP Version: PHP 5.5.9 (`php -v`)
* Operating System: Linux version 3.19.0-32-generic
* Installation type: Compiling from source 
* Server: Nginx | Apache 
* Other related info (Database, table schema): mySql

**Comment by sergeyklay** [comment]
@yesworld Did you try latest stable Phalcon? At least just for test

**Comment by yesworld** [comment]
First I updated to version 3.2.2. It doesn't work.
Then I downgraded to 2.1.0 RC1. It works.
Then tested on versions 3.0.8, 3.0.4 and 3.0.1.  It doesn't work with this parameter too.
```php
 public function initialize(){
       $this->useDynamicUpdate(true);
 }
```

**Comment by sergeyklay** [comment]
@Jurigag Could you please try to sort out?

**Comment by yesworld** [comment]
Any news? @sergeyklay , @Jurigag

**Comment by Jurigag** [comment]
Can't reproduce on phalcon 3.0.2 and on phalcon 3.2.0, please provide steps to reproduce this issue. Are you sure that issue exists on latest phalcon version?

**Comment by Jurigag** [comment]
OH i see it doesn't work with `$this->useDynamicUpdate(true);`

**Comment by Jurigag** [comment]
Well on phalcon 3.2.0 it works properly so i guess issue was fixed already.

**Comment by yesworld** [comment]
@Jurigag 
You didn't do the experiment quite correctly.
If the addition was done once, it's gonna work smooth. 

If you create a new record, it will not work for you.
Try this:
```php
class Users extends \Phalcon\Mvc\Model
{
    public $id;
    public $name;
    public $value=0;
    public function initialize(){
        $this->useDynamicUpdate(true);
    }
}

$Users = new Users();
$Users->value = 0;
$Users->save();

$id = $Users->id;
echo 'id = '. $id ;

var_dump(Users::findFirst( $id )->value);
$query = "UPDATE Users SET value = value + 1 WHERE id = :id:";
$di->get('modelsManager')->createQuery($query)->execute(['id' => $id ]);
$di->get('modelsManager')->createQuery($query)->execute(['id' => $id ]);
$di->get('modelsManager')->createQuery($query)->execute(['id' => $id ]);
var_dump(Users::findFirst( $id )->value);

echo phpversion("phalcon");
```

**Comment by yesworld** [comment]
@Jurigag @sergeyklay 
I tested it on the 3.2.4 version. The issue still exists.

**Comment by Jurigag** [comment]
On 3.3.x branch it works correctly.
