### ISSUE TITLE
Latest windows releases does not work with php7.2

### ISSUE THREAD

**Issue by Ark4ne** [phalcon/cphalcon#13234]
The latest windows releases does not work with php7.2. (TS and NTS)

```
$ /c/php/php7.2.0/php --ri phalcon
Warning: PHP Startup: phalcon: Unable to initialize module
Module compiled with build ID=API20170718,NTS,19.12.25831
PHP    compiled with build ID=API20170718,NTS,VC15
These options need to match
 in Unknown on line 0
PHP 7.2.0 (cli) (built: Nov 28 2017 23:48:32) ( NTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
```

```
$ /c/php/php7.2.0/php --ri phalcon
Warning: PHP Startup: phalcon: Unable to initialize module
Module compiled with build ID=API20170718,NTS,19.12.25831
PHP    compiled with build ID=API20170718,NTS,VC15
These options need to match
 in Unknown on line 0
Extension 'phalcon' not present.
```

### Details
* Phalcon version: 3.3.0
* PHP Version: PHP 7.2.0
* Operating System: Windows 10
* Installation type: Download from github 
* Zephir version (if any): /
* Server: /
* Other related info (Database, table schema):  /

**Comment by maurosys** [comment]
I've same problem.

**Comment by sergeyklay** [comment]
Refs: https://forum.phalconphp.com/discussion/17499/unable-to-initialize-phalcon-33-on-windows-php72

**Comment by niden** [comment]
I can replicate this issue. It is weird because phalcon has been compiled using the sources from php.net. 

I will re-compile the extension with a fresh copy from the sources and let you guys know.

Thanks for the heads up.

**Comment by niden** [comment]
Some progress:

I tried to run `configure` again in the 7.2 folder and noticed this:

```
------------------------------------------------
|                 |                            |
------------------------------------------------
| Build type      | Release                    |
| Thread Safety   | Yes                        |
| Compiler        | MSVC 19.12.25831, untested |
| Architecture    | x64                        |
| Optimization    | PGO disabled               |
| Static analyzer | disabled                   |
------------------------------------------------
```

The Compiler comes from Visual Studion 2017 community edition. I might have to resinstall it or google the results and see where that gets me. If anyone has any thoughts, feel free to contribute.

**Comment by blackjyn** [comment]
God, I'm NOT the only one here
![phalcon error](https://user-images.githubusercontent.com/6046191/34385661-dc301c38-eb56-11e7-8df5-a3ca98d7652c.png)

**Comment by Jurigag** [comment]
I guess you need to compile it with VS15 @niden ?

**Comment by Jurigag** [comment]
```
VC11, VC14 & VC15
More recent versions of PHP are built with VC11, VC14 or VC15 (Visual Studio 2012, 2015 or 2017 compiler respectively) and include improvements in performance and stability.

- The VC11 builds require to have the Visual C++ Redistributable for Visual Studio 2012 x86 or x64 installed

- The VC14 builds require to have the Visual C++ Redistributable for Visual Studio 2015 x86 or x64 installed

- The VC15 builds require to have the Visual C++ Redistributable for Visual Studio 2017 x64 or x86 installed
```

**Comment by sergeyklay** [comment]
As I can see the problem is solved here: https://forum.phalconphp.com/discussion/17499/unable-to-initialize-phalcon-33-on-windows-php72#C53095

Has anybody tried such an approach?

**Comment by blackjyn** [comment]
No I haven't tried that 
Compiling from the source is non-trivial for me

**Comment by echodreamz** [comment]
Same issue here, compiling is not something that I can really do. However I did redownload again today and the issue persists with x64 / NTS.

**Comment by sergeyklay** [comment]
@niden Is there any news?

**Comment by niden** [comment]
New DLLs have been compiled for 7.2 and they now report the correct version.  (see release page)

Please let us know if that resolved the issue.

**Comment by lubber-de** [comment]
@niden Yes, it works for me now. Thanks a lot and happy new year

**Comment by echodreamz** [comment]
Confirmed - Is now working! THank you!

**Comment by blackjyn** [comment]
IT WORKS NOW!  Thank you!
I'm on Windows 8.1 x64, using XAMPP PHP 7.2 , Phalcon 3.3 TS

Happy new year Y'all!!!! 😄 🎺 🎆 🎆 🎆 
![phalcon 33 works](https://user-images.githubusercontent.com/6046191/34459212-0504c09c-ee1c-11e7-8225-d914aff399ab.png)

**Comment by niden** [comment]
Closing this issue :)

**Comment by chisumo2016** [comment]
Hi 

I am still finding the problem with extension.When i run php info i can see phalcon but if i try to run the command phalcon in cmd it slow error.pls hel

**Comment by chisumo2016** [comment]
I have been struggling for 5 days to install phalcon to my pc window 7 .when i open php.ini i can not find the list of all dll.I am running on php 7.1

**Comment by salva-flores** [comment]
Hello,
I just downloaded phalcon_x86_vc15_php7.2.0_3.3.0
And after installation i get this error...

C:\xampp\php>php -v
PHP Warning:  PHP Startup: phalcon: Unable to initialize module
Module compiled with build ID=API20170718,TS,19.12.25831
PHP    compiled with build ID=API20170718,TS,VC15
These options need to match
 in Unknown on line 0

Warning: PHP Startup: phalcon: Unable to initialize module
Module compiled with build ID=API20170718,TS,19.12.25831
PHP    compiled with build ID=API20170718,TS,VC15
These options need to match
 in Unknown on line 0
PHP 7.2.5 (cli) (built: Apr 25 2018 02:39:21) ( ZTS MSVC15 (Visual C++ 2017) x86 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

Please help.

**Comment by salva-flores** [comment]
I finally got the right one...
phalcon_x86_vc15_php7.2.0_3.3.0
This one works fine...
