### ISSUE TITLE
Tons of "Declaration of ... must be compatible with..."

### ISSUE THREAD

**Issue by remicollet** [phalcon/cphalcon#13465]
phalcon **3.4.1** build using latest zephir **0.11.0**

```
$ php -v
PHP Fatal error:  Declaration of Phalcon\Forms\Element::getAttribute(string $attribute, $defaultValue = NULL) must be compatible with Phalcon\Forms\ElementInterface::getAttribute($attribute, $defaultValue = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend::stop(?bool $stopBuffer = NULL) must be compatible with Phalcon\Cache\BackendInterface::stop($stopBuffer = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData::readMetaDataIndex(Phalcon\Mvc\ModelInterface $model, int $index) must be compatible with Phalcon\Mvc\Model\MetaDataInterface::readMetaDataIndex(Phalcon\Mvc\ModelInterface $model, $index) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData::writeMetaDataIndex(Phalcon\Mvc\ModelInterface $model, int $index, $data) must be compatible with Phalcon\Mvc\Model\MetaDataInterface::writeMetaDataIndex(Phalcon\Mvc\ModelInterface $model, $index, $data) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData::readColumnMapIndex(Phalcon\Mvc\ModelInterface $model, int $index) must be compatible with Phalcon\Mvc\Model\MetaDataInterface::readColumnMapIndex(Phalcon\Mvc\ModelInterface $model, $index) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Db\Adapter::limit(string $sqlQuery, int $number): string must be compatible with Phalcon\Db\AdapterInterface::limit($sqlQuery, $number) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Db\Adapter::createView(string $viewName, array $definition, $schemaName = NULL): bool must be compatible with Phalcon\Db\AdapterInterface::createView(string $viewName, array $definition, ?string $schemaName = NULL): bool in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Db\Adapter::dropIndex(string $tableName, string $schemaName, $indexName): bool must be compatible with Phalcon\Db\AdapterInterface::dropIndex(string $tableName, string $schemaName, string $indexName): bool in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Db\Adapter::describeIndexes(string $table, $schema = NULL) must be compatible with Phalcon\Db\AdapterInterface::describeIndexes(string $table, ?string $schema = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Assets\Inline::getType() must be compatible with Phalcon\Assets\ResourceInterface::getType(): string in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Assets\Inline::getFilter() must be compatible with Phalcon\Assets\ResourceInterface::getFilter(): bool in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Assets\Inline::getAttributes() must be compatible with Phalcon\Assets\ResourceInterface::getAttributes(): ?null in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Assets\Resource::getFilter(): null must be compatible with Phalcon\Assets\ResourceInterface::getFilter(): bool in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Di::offsetExists(string $name): bool must be compatible with ArrayAccess::offsetExists($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Di::offsetGet(string $name): null must be compatible with ArrayAccess::offsetGet($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Di::offsetSet(string $name, $definition): bool must be compatible with ArrayAccess::offsetSet($offset, $value) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Di::offsetUnset(string $name): bool must be compatible with ArrayAccess::offsetUnset($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Image\Adapter::text(string $text, $offsetX = NULL, $offsetY = NULL, ?int $opacity = NULL, ?string $color = NULL, ?int $size = NULL, ?string $fontfile = NULL) must be compatible with Phalcon\Image\AdapterInterface::text(string $text, ?int $offsetX = NULL, ?int $offsetY = NULL, ?int $opacity = NULL, ?string $color = NULL, ?int $size = NULL, ?string $fontfile = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Resultset::seek(int $position) must be compatible with SeekableIterator::seek($position) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Resultset::offsetExists(int $index): bool must be compatible with ArrayAccess::offsetExists($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Resultset::offsetGet(int $index) must be compatible with ArrayAccess::offsetGet($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Resultset::offsetUnset(int $offset) must be compatible with ArrayAccess::offsetUnset($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\View\Engine::getContent(): string must be compatible with Phalcon\Mvc\View\EngineInterface::getContent(): null in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Acl\Adapter::getActiveRole(): null must be compatible with Phalcon\Acl\AdapterInterface::getActiveRole(): string in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Acl\Adapter::getActiveResource(): null must be compatible with Phalcon\Acl\AdapterInterface::getActiveResource(): string in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Acl\Adapter::getActiveAccess(): null must be compatible with Phalcon\Acl\AdapterInterface::getActiveAccess(): string in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Acl\Adapter\Memory::isAllowed($roleName, $resourceName, string $access, ?array $parameters = NULL): bool must be compatible with Phalcon\Acl\AdapterInterface::isAllowed($roleName, $resourceName, $access, ?array $parameters = NULL): bool in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\Apc::save($keyName = NULL, $content = NULL, $lifetime = NULL, ?bool $stopBuffer = NULL): bool must be compatible with Phalcon\Cache\BackendInterface::save($keyName = NULL, $content = NULL, $lifetime = NULL, $stopBuffer = NULL): bool in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\Apc::delete(string $keyName): bool must be compatible with Phalcon\Cache\BackendInterface::delete($keyName) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\Apc::queryKeys(?string $prefix = NULL): null must be compatible with Phalcon\Cache\BackendInterface::queryKeys($prefix = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\Apcu::save($keyName = NULL, $content = NULL, $lifetime = NULL, ?bool $stopBuffer = NULL): bool must be compatible with Phalcon\Cache\BackendInterface::save($keyName = NULL, $content = NULL, $lifetime = NULL, $stopBuffer = NULL): bool in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\Apcu::delete(string $keyName): bool must be compatible with Phalcon\Cache\BackendInterface::delete($keyName) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\Apcu::queryKeys(?string $prefix = NULL): null must be compatible with Phalcon\Cache\BackendInterface::queryKeys($prefix = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\File::save($keyName = NULL, $content = NULL, $lifetime = NULL, ?bool $stopBuffer = NULL): bool must be compatible with Phalcon\Cache\BackendInterface::save($keyName = NULL, $content = NULL, $lifetime = NULL, $stopBuffer = NULL): bool in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\File::queryKeys(?string $prefix = NULL): null must be compatible with Phalcon\Cache\BackendInterface::queryKeys($prefix = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\File::exists($keyName = NULL, ?int $lifetime = NULL): bool must be compatible with Phalcon\Cache\BackendInterface::exists($keyName = NULL, $lifetime = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\Libmemcached::save($keyName = NULL, $content = NULL, $lifetime = NULL, ?bool $stopBuffer = NULL): bool must be compatible with Phalcon\Cache\BackendInterface::save($keyName = NULL, $content = NULL, $lifetime = NULL, $stopBuffer = NULL): bool in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\Libmemcached::queryKeys(?string $prefix = NULL): null must be compatible with Phalcon\Cache\BackendInterface::queryKeys($prefix = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\Memcache::save($keyName = NULL, $content = NULL, $lifetime = NULL, ?bool $stopBuffer = NULL): bool must be compatible with Phalcon\Cache\BackendInterface::save($keyName = NULL, $content = NULL, $lifetime = NULL, $stopBuffer = NULL): bool in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\Memcache::queryKeys(?string $prefix = NULL): null must be compatible with Phalcon\Cache\BackendInterface::queryKeys($prefix = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\Memory::save($keyName = NULL, $content = NULL, $lifetime = NULL, ?bool $stopBuffer = NULL): bool must be compatible with Phalcon\Cache\BackendInterface::save($keyName = NULL, $content = NULL, $lifetime = NULL, $stopBuffer = NULL): bool in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\Memory::queryKeys(?string $prefix = NULL): null must be compatible with Phalcon\Cache\BackendInterface::queryKeys($prefix = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\Mongo::save($keyName = NULL, $content = NULL, $lifetime = NULL, ?bool $stopBuffer = NULL): bool must be compatible with Phalcon\Cache\BackendInterface::save($keyName = NULL, $content = NULL, $lifetime = NULL, $stopBuffer = NULL): bool in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\Mongo::queryKeys(?string $prefix = NULL): null must be compatible with Phalcon\Cache\BackendInterface::queryKeys($prefix = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\Redis::save($keyName = NULL, $content = NULL, $lifetime = NULL, ?bool $stopBuffer = NULL): bool must be compatible with Phalcon\Cache\BackendInterface::save($keyName = NULL, $content = NULL, $lifetime = NULL, $stopBuffer = NULL): bool in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\Redis::queryKeys(?string $prefix = NULL): null must be compatible with Phalcon\Cache\BackendInterface::queryKeys($prefix = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\Xcache::save($keyName = NULL, $content = NULL, $lifetime = NULL, ?bool $stopBuffer = NULL): bool must be compatible with Phalcon\Cache\BackendInterface::save($keyName = NULL, $content = NULL, $lifetime = NULL, $stopBuffer = NULL): bool in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Cache\Backend\Xcache::queryKeys(?string $prefix = NULL): null must be compatible with Phalcon\Cache\BackendInterface::queryKeys($prefix = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Crypt::encrypt(string $text, ?string $key = NULL): string must be compatible with Phalcon\CryptInterface::encrypt(string $text, $key = NULL): string in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Db\Adapter\Pdo\Mysql::describeIndexes(string $table, $schema = NULL) must be compatible with Phalcon\Db\AdapterInterface::describeIndexes(string $table, ?string $schema = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Db\Adapter\Pdo\Sqlite::describeIndexes($table, $schema = NULL) must be compatible with Phalcon\Db\AdapterInterface::describeIndexes(string $table, ?string $schema = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Db\Adapter\Pdo\Sqlite::describeReferences($table, $schema = NULL) must be compatible with Phalcon\Db\AdapterInterface::describeReferences(string $table, ?string $schema = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Db\Result\Pdo::dataSeek(int $number) must be compatible with Phalcon\Db\ResultInterface::dataSeek($number) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Db\Result\Pdo::setFetchMode(int $fetchMode, $colNoOrClassNameOrObject = NULL, $ctorargs = NULL): bool must be compatible with Phalcon\Db\ResultInterface::setFetchMode($fetchMode): bool in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Escaper::setEncoding(string $encoding) must be compatible with Phalcon\EscaperInterface::setEncoding($encoding) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Escaper::setHtmlQuoteType(int $quoteType) must be compatible with Phalcon\EscaperInterface::setHtmlQuoteType($quoteType) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Escaper::escapeHtml(string $text): string must be compatible with Phalcon\EscaperInterface::escapeHtml($text) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Escaper::escapeHtmlAttr(string $attribute): string must be compatible with Phalcon\EscaperInterface::escapeHtmlAttr($text) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Escaper::escapeCss(string $css): string must be compatible with Phalcon\EscaperInterface::escapeCss($css) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Escaper::escapeJs(string $js): string must be compatible with Phalcon\EscaperInterface::escapeJs($js) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Escaper::escapeUrl(string $url): string must be compatible with Phalcon\EscaperInterface::escapeUrl($url) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Events\Event::getType(): string must be compatible with Phalcon\Events\EventInterface::getType(): null in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Flash\Session::message(string $type, string $message) must be compatible with Phalcon\FlashInterface::message(string $type, $message) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Http\Request::hasFiles(?bool $onlySuccessful = NULL): int must be compatible with Phalcon\Http\RequestInterface::hasFiles($onlySuccessful = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Logger\Formatter\Syslog::format($message, int $type, int $timestamp, $context = NULL): null must be compatible with Phalcon\Logger\FormatterInterface::format(string $message, int $type, int $timestamp, $context = NULL): string in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Collection::unserialize(string $data) must be compatible with Serializable::unserialize($serialized) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Collection\Document::readAttribute($attribute) must be compatible with Phalcon\Mvc\EntityInterface::readAttribute(string $attribute) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Collection\Document::offsetExists(string $index): bool must be compatible with ArrayAccess::offsetExists($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Collection\Document::offsetGet(string $index) must be compatible with ArrayAccess::offsetGet($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Collection\Document::offsetSet(string $index, $value) must be compatible with ArrayAccess::offsetSet($offset, $value) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model::cloneResultMap($base, array $data, $columnMap, ?int $dirtyState = NULL, ?bool $keepSnapshots = NULL) must be compatible with Phalcon\Mvc\ModelInterface::cloneResultMap($base, array $data, $columnMap, $dirtyState = NULL, $keepSnapshots = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model::cloneResult(Phalcon\Mvc\ModelInterface $base, array $data, ?int $dirtyState = NULL) must be compatible with Phalcon\Mvc\ModelInterface::cloneResult(Phalcon\Mvc\ModelInterface $base, array $data, $dirtyState = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model::fireEvent(string $eventName): bool must be compatible with Phalcon\Mvc\ModelInterface::fireEvent($eventName) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model::fireEventCancel(string $eventName): bool must be compatible with Phalcon\Mvc\ModelInterface::fireEventCancel($eventName) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model::getRelated(string $alias, $arguments = NULL) must be compatible with Phalcon\Mvc\ModelInterface::getRelated($alias, $arguments = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model::setDirtyState(int $dirtyState) must be compatible with Phalcon\Mvc\Model\ResultInterface::setDirtyState($dirtyState) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model::unserialize(string $data) must be compatible with Serializable::unserialize($serialized) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Binder::bindToHandler($handler, array $params, string $cacheKey, $methodName = NULL): null must be compatible with Phalcon\Mvc\Model\BinderInterface::bindToHandler($handler, array $params, string $cacheKey, ?string $methodName = NULL): null in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Manager::addHasOne(Phalcon\Mvc\ModelInterface $model, $fields, string $referencedModel, $referencedFields, $options = NULL) must be compatible with Phalcon\Mvc\Model\ManagerInterface::addHasOne(Phalcon\Mvc\ModelInterface $model, $fields, $referencedModel, $referencedFields, $options = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Manager::addBelongsTo(Phalcon\Mvc\ModelInterface $model, $fields, string $referencedModel, $referencedFields, $options = NULL) must be compatible with Phalcon\Mvc\Model\ManagerInterface::addBelongsTo(Phalcon\Mvc\ModelInterface $model, $fields, $referencedModel, $referencedFields, $options = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Manager::addHasMany(Phalcon\Mvc\ModelInterface $model, $fields, string $referencedModel, $referencedFields, $options = NULL) must be compatible with Phalcon\Mvc\Model\ManagerInterface::addHasMany(Phalcon\Mvc\ModelInterface $model, $fields, $referencedModel, $referencedFields, $options = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Manager::existsBelongsTo(string $modelName, string $modelRelation): bool must be compatible with Phalcon\Mvc\Model\ManagerInterface::existsBelongsTo($modelName, $modelRelation) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Manager::existsHasMany(string $modelName, string $modelRelation): bool must be compatible with Phalcon\Mvc\Model\ManagerInterface::existsHasMany($modelName, $modelRelation) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Manager::existsHasOne(string $modelName, string $modelRelation): bool must be compatible with Phalcon\Mvc\Model\ManagerInterface::existsHasOne($modelName, $modelRelation) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Manager::getBelongsToRecords(string $method, string $modelName, $modelRelation, Phalcon\Mvc\ModelInterface $record, $parameters = NULL) must be compatible with Phalcon\Mvc\Model\ManagerInterface::getBelongsToRecords($method, $modelName, $modelRelation, Phalcon\Mvc\ModelInterface $record, $parameters = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Manager::getHasManyRecords(string $method, string $modelName, $modelRelation, Phalcon\Mvc\ModelInterface $record, $parameters = NULL) must be compatible with Phalcon\Mvc\Model\ManagerInterface::getHasManyRecords($method, $modelName, $modelRelation, Phalcon\Mvc\ModelInterface $record, $parameters = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Manager::getHasOneRecords(string $method, string $modelName, $modelRelation, Phalcon\Mvc\ModelInterface $record, $parameters = NULL) must be compatible with Phalcon\Mvc\Model\ManagerInterface::getHasOneRecords($method, $modelName, $modelRelation, Phalcon\Mvc\ModelInterface $record, $parameters = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Manager::getRelations(string $modelName) must be compatible with Phalcon\Mvc\Model\ManagerInterface::getRelations($modelName) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Manager::getRelationsBetween(string $first, string $second) must be compatible with Phalcon\Mvc\Model\ManagerInterface::getRelationsBetween($first, $second) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Manager::createQuery(string $phql) must be compatible with Phalcon\Mvc\Model\ManagerInterface::createQuery($phql) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Manager::executeQuery(string $phql, $placeholders = NULL, $types = NULL) must be compatible with Phalcon\Mvc\Model\ManagerInterface::executeQuery($phql, $placeholders = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Manager::notifyEvent(string $eventName, Phalcon\Mvc\ModelInterface $model) must be compatible with Phalcon\Mvc\Model\ManagerInterface::notifyEvent($eventName, Phalcon\Mvc\ModelInterface $model) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Manager::missingMethod(Phalcon\Mvc\ModelInterface $model, string $eventName, $data) must be compatible with Phalcon\Mvc\Model\ManagerInterface::missingMethod(Phalcon\Mvc\ModelInterface $model, $eventName, $data) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Message::setType(string $type) must be compatible with Phalcon\Mvc\Model\MessageInterface::setType($type) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Message::setMessage(string $message) must be compatible with Phalcon\Mvc\Model\MessageInterface::setMessage($message) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData\Apc::read(string $key): ?null must be compatible with Phalcon\Mvc\Model\MetaDataInterface::read($key) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData\Apc::write(string $key, $data) must be compatible with Phalcon\Mvc\Model\MetaDataInterface::write($key, $data) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData\Apcu::read(string $key): ?null must be compatible with Phalcon\Mvc\Model\MetaDataInterface::read($key) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData\Apcu::write(string $key, $data) must be compatible with Phalcon\Mvc\Model\MetaDataInterface::write($key, $data) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData\Files::read(string $key) must be compatible with Phalcon\Mvc\Model\MetaDataInterface::read($key) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData\Files::write(string $key, $data) must be compatible with Phalcon\Mvc\Model\MetaDataInterface::write($key, $data) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData\Libmemcached::read(string $key): ?null must be compatible with Phalcon\Mvc\Model\MetaDataInterface::read($key) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData\Libmemcached::write(string $key, $data) must be compatible with Phalcon\Mvc\Model\MetaDataInterface::write($key, $data) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData\Memcache::read(string $key): ?null must be compatible with Phalcon\Mvc\Model\MetaDataInterface::read($key) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData\Memcache::write(string $key, $data) must be compatible with Phalcon\Mvc\Model\MetaDataInterface::write($key, $data) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData\Memory::read(string $key) must be compatible with Phalcon\Mvc\Model\MetaDataInterface::read($key) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData\Memory::write(string $key, $data) must be compatible with Phalcon\Mvc\Model\MetaDataInterface::write($key, $data) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData\Redis::read(string $key): ?null must be compatible with Phalcon\Mvc\Model\MetaDataInterface::read($key) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData\Redis::write(string $key, $data) must be compatible with Phalcon\Mvc\Model\MetaDataInterface::write($key, $data) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData\Session::read(string $key) must be compatible with Phalcon\Mvc\Model\MetaDataInterface::read($key) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData\Session::write(string $key, $data) must be compatible with Phalcon\Mvc\Model\MetaDataInterface::write($key, $data) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData\Xcache::read(string $key) must be compatible with Phalcon\Mvc\Model\MetaDataInterface::read($key) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\MetaData\Xcache::write(string $key, $data) must be compatible with Phalcon\Mvc\Model\MetaDataInterface::write($key, $data) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Query\Builder::join(string $model, $conditions = NULL, $alias = NULL, $type = NULL) must be compatible with Phalcon\Mvc\Model\Query\BuilderInterface::join($model, $conditions = NULL, $alias = NULL, $type = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Query\Builder::innerJoin(string $model, $conditions = NULL, $alias = NULL) must be compatible with Phalcon\Mvc\Model\Query\BuilderInterface::innerJoin($model, $conditions = NULL, $alias = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Query\Builder::leftJoin(string $model, $conditions = NULL, $alias = NULL) must be compatible with Phalcon\Mvc\Model\Query\BuilderInterface::leftJoin($model, $conditions = NULL, $alias = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Query\Builder::rightJoin(string $model, $conditions = NULL, $alias = NULL) must be compatible with Phalcon\Mvc\Model\Query\BuilderInterface::rightJoin($model, $conditions = NULL, $alias = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Query\Builder::andWhere(string $conditions, $bindParams = NULL, $bindTypes = NULL) must be compatible with Phalcon\Mvc\Model\Query\BuilderInterface::andWhere($conditions, $bindParams = NULL, $bindTypes = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Query\Builder::orWhere(string $conditions, $bindParams = NULL, $bindTypes = NULL) must be compatible with Phalcon\Mvc\Model\Query\BuilderInterface::orWhere($conditions, $bindParams = NULL, $bindTypes = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Query\Builder::betweenWhere(string $expr, $minimum, $maximum, ?string $operator = NULL) must be compatible with Phalcon\Mvc\Model\Query\BuilderInterface::betweenWhere($expr, $minimum, $maximum, ?string $operator = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Query\Builder::notBetweenWhere(string $expr, $minimum, $maximum, ?string $operator = NULL) must be compatible with Phalcon\Mvc\Model\Query\BuilderInterface::notBetweenWhere($expr, $minimum, $maximum, ?string $operator = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Resultset\Complex::unserialize(string $data) must be compatible with Serializable::unserialize($serialized) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Resultset\Simple::unserialize(string $data) must be compatible with Serializable::unserialize($serialized) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Row::readAttribute($attribute) must be compatible with Phalcon\Mvc\EntityInterface::readAttribute(string $attribute) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Row::setDirtyState(int $dirtyState): bool must be compatible with Phalcon\Mvc\Model\ResultInterface::setDirtyState($dirtyState) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Row::offsetUnset(int $offset) must be compatible with ArrayAccess::offsetUnset($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Model\Transaction::rollback($rollbackMessage = NULL, ?Phalcon\Mvc\ModelInterface $rollbackRecord = NULL): bool must be compatible with Phalcon\Mvc\Model\TransactionInterface::rollback(?string $rollbackMessage = NULL, ?Phalcon\Mvc\ModelInterface $rollbackRecord = NULL) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Url::get($uri = NULL, $args = NULL, $local = NULL, $baseUri = NULL): string must be compatible with Phalcon\Mvc\UrlInterface::get($uri = NULL, $args = NULL, ?bool $local = NULL): string in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\Url::path(?string $path = NULL): string must be compatible with Phalcon\Mvc\UrlInterface::path($path = NULL): string in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\View::setRenderLevel(int $level) must be compatible with Phalcon\Mvc\ViewInterface::setRenderLevel(string $level) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\View::pick($renderView) must be compatible with Phalcon\Mvc\ViewInterface::pick(string $renderView) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\View::setViewsDir($viewsDir) must be compatible with Phalcon\Mvc\ViewBaseInterface::setViewsDir(string $viewsDir) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\View::partial(string $partialPath, $params = NULL) must be compatible with Phalcon\Mvc\ViewBaseInterface::partial(string $partialPath, $params = NULL): string in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\View\Simple::getParamsToView() must be compatible with Phalcon\Mvc\ViewBaseInterface::getParamsToView(): null in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Mvc\View\Simple::partial(string $partialPath, $params = NULL) must be compatible with Phalcon\Mvc\ViewBaseInterface::partial(string $partialPath, $params = NULL): string in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Registry::offsetExists(string $offset): bool must be compatible with ArrayAccess::offsetExists($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Registry::offsetGet(string $offset): null must be compatible with ArrayAccess::offsetGet($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Registry::offsetSet(string $offset, $value) must be compatible with ArrayAccess::offsetSet($offset, $value) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Registry::offsetUnset(string $offset) must be compatible with ArrayAccess::offsetUnset($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Session\Adapter\Libmemcached::destroy(?string $sessionId = NULL): bool must be compatible with Phalcon\Session\AdapterInterface::destroy(?bool $removeData = NULL): bool in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Session\Adapter\Memcache::destroy(?string $sessionId = NULL): bool must be compatible with Phalcon\Session\AdapterInterface::destroy(?bool $removeData = NULL): bool in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Session\Adapter\Redis::destroy(?string $sessionId = NULL): bool must be compatible with Phalcon\Session\AdapterInterface::destroy(?bool $removeData = NULL): bool in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Session\Bag::get(string $property, $defaultValue = NULL) must be compatible with Phalcon\Session\BagInterface::get(string $property, $defaultValue = NULL): null in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Session\Bag::offsetExists(string $property): bool must be compatible with ArrayAccess::offsetExists($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Session\Bag::offsetGet(string $property): null must be compatible with ArrayAccess::offsetGet($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Session\Bag::offsetSet(string $property, $value) must be compatible with ArrayAccess::offsetSet($offset, $value) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Session\Bag::offsetUnset(string $property) must be compatible with ArrayAccess::offsetUnset($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Translate\Adapter::offsetExists(string $translateKey): bool must be compatible with ArrayAccess::offsetExists($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Translate\Adapter::offsetGet(string $translateKey) must be compatible with ArrayAccess::offsetGet($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Translate\Adapter::offsetExists(string $translateKey): bool must be compatible with ArrayAccess::offsetExists($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Translate\Adapter::offsetGet(string $translateKey) must be compatible with ArrayAccess::offsetGet($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Translate\Adapter::offsetExists(string $translateKey): bool must be compatible with ArrayAccess::offsetExists($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Translate\Adapter::offsetGet(string $translateKey) must be compatible with ArrayAccess::offsetGet($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Validation::add($field, Phalcon\Validation\ValidatorInterface $validator) must be compatible with Phalcon\ValidationInterface::add(string $field, Phalcon\Validation\ValidatorInterface $validator) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Validation::rule($field, Phalcon\Validation\ValidatorInterface $validator) must be compatible with Phalcon\ValidationInterface::rule(string $field, Phalcon\Validation\ValidatorInterface $validator) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Validation::rules($field, array $validators) must be compatible with Phalcon\ValidationInterface::rules(string $field, array $validators) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Validation::setFilters($field, $filters) must be compatible with Phalcon\ValidationInterface::setFilters(string $field, $filters) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Validation::getLabel($field) must be compatible with Phalcon\ValidationInterface::getLabel(string $field) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Validation\Message::setField($field) must be compatible with Phalcon\Validation\MessageInterface::setField(string $field) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Validation\Message\Group::offsetExists(string $index): bool must be compatible with ArrayAccess::offsetExists($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Validation\Message\Group::offsetGet(int $index) must be compatible with ArrayAccess::offsetGet($offset) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Validation\Message\Group::offsetSet(int $index, $message) must be compatible with ArrayAccess::offsetSet($offset, $value) in Unknown on line 0
PHP Fatal error:  Declaration of Phalcon\Validation\Validator\Uniqueness::validate(Phalcon\Validation $validation, $field): bool must be compatible with Phalcon\Validation\Validator::validate(Phalcon\Validation $validation, string $attribute): bool in Unknown on line 0
PHP 7.1.21 (cli) (built: Aug 14 2018 17:18:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.21, Copyright (c) 1999-2018, by Zend Technologies

```

**Comment by Jurigag** [comment]
@AlexNDRmac @sergeyklay any idea what's going on?

**Comment by AlexNDRmac** [comment]
Maybe some trouble with `strict type`... maybe - not... Are there any details or steps to reproduce this?

**Comment by remicollet** [comment]
@AlexDRiVER see issue description... reproducer is: `php -v`

**Comment by stamster** [comment]
We only see it's NTS version. Which OS do you use?

I have no issues with 3.4.1.


```
Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.4.1
Build Date => Aug  6 2018 05:34:37
Powered by Zephir => Version 0.10.10-d1b4cc68d9
```

**Comment by Jurigag** [comment]
Well i already know what's going on, you must compile phalcon 3.4 with zephir 0.10.x @remicollet https://github.com/phalcon/zephir/issues/1656#issuecomment-410452749 for phalcon 4 we will update all classes and their interfaces to have same types, but for not break anything in phalcon 3.4 we can't do this.

**Comment by stamster** [comment]
So the issue is withing Zephir 0.11?

**Comment by sergeyklay** [comment]
@stamster Please use Zephir 0.10.x to compile Phalcon 3.4.x. The Phalcon 4.0.x branch was fixed and ready to be compiled using Zephir 0.11.x as well as 0.10.x (see #13589).

**Comment by SmartyGunjan** [comment]
I got single error on phalcon 4 andphp 7.2


Fatal error: Declaration of Calculator::__isset($property) must be compatible with Phalcon\Mvc\Model::__isset(string $property): bool in /usr/share/nginx/html/luminous_api/models/Calculator.php on line 686

**Comment by Jeckerson** [comment]
@SmartyGunjan you forgot `: bool` at the end of method declaration?
