### ISSUE TITLE
allowEmptyStringValues() does not accept custom property/column names

### ISSUE THREAD

**Issue by mohahn** [phalcon/cphalcon#13477]
I'm using Phalcon 3.4.0
Regarding [#440](https://github.com/phalcon/cphalcon/issues/440) I'm not happy with the solution of using `allowEmptyStringValues()` but as it's the only solution it should use custom property names.
When using a database table with underscore in column names (i.e. `match_type`) I'm able to create the following model

```
class Campaign extends Model {
   protected $matchType;
   public function columnMap() {
      return [ 'match_type' => 'matchType' ];
   }
}
```

When defining relationships inside `initialize()` method I'm able to use this camel-case notation for columns, but when using `allowEmptyStringValues([ 'matchType' ])` this does not work. I'm still getting validation error, that `matchType is required`. This empty-string workaround is only working when using real table column names, like `allowEmptyStringValues([ 'match_type' ])`.
So when I'm allowed to use camel-case notation for defining relationships to other models, I should be able to use property names defined by `columnMap()` in `allowEmptyStringValues()`, also. Please change this behaviour.

**Comment by CameronHall** [comment]
@niden I may as well fix this when I do #12975

**Comment by niden** [comment]
Addressed in https://github.com/phalcon/cphalcon/pull/13692

**Comment by wurst-hans** [comment]
This is still an issue in Phalcon 4.0.4
`allowEmptyStringValues` does not recognize `columnMap()` I have to use real column name instead.

**Comment by ros-infobest** [comment]
allowEmptyStringValues(), from the name it does not allow empty string but it exclude column from update so, would be good to have name something like excludeColumnFromUpdate() or other name that is previle its name as it do.
