### ISSUE TITLE
[BUG]: Fatal error in the model

### ISSUE THREAD

**Issue by ekmst** [phalcon/cphalcon#14617]
**Fatal error: Uncaught ErrorException: array_flip(): Can only flip STRING and INTEGER values! in /path/to/app/common/Models/Users.php on line ...**

I just call the method `Model::findFirst()`

```php
$user = Users::findFirst(12);
```

**Details**
 - Phalcon version:
``` 
phalcon => enabled
Author => Phalcon Team and contributors
Version => 4.0.0
Build Date => Dec 12 2019 19:34:29
Powered by Zephir => Version 0.12.10-fedc314
Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.case_insensitive_column_map => Off => Off
phalcon.orm.cast_last_insert_id_to_int => Off => Off
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.column_renaming => On => On
phalcon.orm.disable_assign_setters => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.enable_literals => On => On
phalcon.orm.events => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.exception_on_failed_metadata_save => On => On
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.not_null_validations => On => On
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.warning.enable => On => On
```
 - PHP Version: `7.3.12`
 - Operating System: ubuntu
 - Installation type: Compiling from source
 - Zephir version (if any):
 - Server: Nginx
 - Other related info (Database, table schema): Mysql

Users model
```php
class Users extends \Phalcon\Mvc\Model
{
    // fields
    // getters/setters

    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }
}
```

Stack trace:
```
#0 [internal function]: App\ErrorHandlers->errorHandler(2, 'array_flip(): C...', '/home/dev/w...', 370, Array)
#1 [internal function]: array_flip(Array)
#2 [internal function]: Phalcon\Mvc\Model::cloneResultMap(Object(App\Models\Users), Array, Array, 0, false)
#3 [internal function]: Phalcon\Mvc\Model\Resultset\Simple->current()
#4 [internal function]: Phalcon\Mvc\Model\Resultset->getFirst()
#5 [internal function]: Phalcon\Mvc\Model\Query->execute()
#6 /path/to/app/app/common/models/Users.php(370): Phalcon\Mvc\Model::findFirst(Array)
#7 /path/to/app/app/modules/frontend/controllers/UserController.php(11): Demo\Models\Users::findFirst(Array)
#8 [internal function]: App\Modules\Frontend\Controllers\UserController->imagesAction('12')
#9 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(App\Modules\Frontend\Controllers\UserController), 'imagesAction', Array)
#10 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#11 /path/to/app/app/bootstrap/WebApplication.php(64): Phalcon\Mvc\Application->handle('/user/12')
#12 /path/to/app/app/bootstrap_web.php(7): App\Bootstrap\WebApplication->run()
#13 /path/to/app/public/index.php(2): require_once('/home/dev/w...')
#14 {main}
```

**Comment by ruudboon** [comment]
Can you post you user model as well?

**Comment by ekmst** [comment]
> Can you post you user model as well?

done

**Comment by ruudboon** [comment]
@ekmst thnx. We will have a look

**Comment by ekmst** [comment]
@ruudboon 
In version 4.0.0-RC.3 it worked.
I think this is due to these changes https://github.com/phalcon/cphalcon/commit/dbbfb2ba6f1773012acc43fe3f786809eef263eb#diff-ccd168600cf3b8dad821085625fbb273R772

**Comment by ruudboon** [comment]
@niden Can you have a go at this one? If you need some help with a test for this ping me.

**Comment by niden** [comment]
Addressed in https://github.com/phalcon/cphalcon/pull/14619

Thanks @ekmst

**Comment by ekmst** [comment]
@niden 

Thank you guys for the quick fix!

**Comment by zsilbi** [comment]
@niden:
> Addressed in #14619

Unfortunately this did not solve the problem because the real reason `array_flip()` fails is that it gets an array for input like this:

```
Array
(
    [id] => Array
        (
            [0] => code
            [1] => 0
        )

    [email] => Array
        (
            [0] => emailAddress
            [1] => 2
        )
)
```
This array is created by `Mvc\Model\Query` when the `Resultset` is being hydrated.
I'll create a new a PR to fix this in the `Model`.

**Comment by Jeckerson** [comment]
Fixed in `4.1.x` branch.

**Comment by zsilbi** [comment]
@Jeckerson, it's not yet in 4.1.x
I have just made a PR https://github.com/phalcon/cphalcon/pull/15161

**Comment by zsilbi** [comment]
Fixed in https://github.com/phalcon/cphalcon/pull/15161
