### ISSUE TITLE
[BUG]: Logger test fails randomly 

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#14717]
Our master branch often fails during our nightly run.
This is caused by the test using the time as assert see: https://travis-ci.org/phalcon/cphalcon/jobs/637735755

@jenovateurs Can you have a look at this one?

**Comment by jenovateurs** [comment]
@ruudboon Yes, I can :-)

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14718

**Comment by ruudboon** [comment]
@jenovateurs Still seeing some issues. Maybe it fails on whole numbers and probably when you run exactly on the hour / day as well. Maybe we can convert it to a Datetime object and calculate diff?  
```
$datetime1 = new DateTime('2009-10-11');
$datetime2 = new DateTime('2009-10-13');
$interval = $datetime1->diff($datetime2)->format('%s');
```

 https://github.com/ruudboon/cphalcon/runs/399106964#step:13:129

**Comment by jenovateurs** [comment]
@ruudboon ok no problem, I will try that and add a threshold to accept the value

**Comment by ruudboon** [comment]
Fixed
