### ISSUE TITLE
[BUG]: $response->setStatusCode() doesn't set the status code (Phalcon 5.0.0alpha)

### ISSUE THREAD

**Issue by destyk** [phalcon/cphalcon#15836]
The ```$this->response->setStatusCode(code)``` function being called doesn't set the request status I needed when I upgraded to Phalcon 5.0.0. Before that I used version Phalcon 3.4 and my code worked. The same problem is observed with the ```$this->response->setContentType()``` method. This issue is relevant in the `$app->before()` event.

```php
/* app.php */
// ...
$app->before(
    new AccessMiddleware()
);
```
```php
/* AccessMiddleware.php */
public function call(Phalcon\Mvc\Micro $app)
{
    $body = [ 'test' => 123 ];
    
    // Tried $this as well but no change 
    $app->response
        ->setStatusCode(404)
        ->setContentType('application/json', 'UTF-8')
        ->setJsonContent($body, JSON_NUMERIC_CHECK)
        ->send();
    exit();
}
```

**Expected behavior**
The executed code above should set the response status to ```404``` and the Content-Type to ```application/json; charset=UTF-8```, however, instead of this:

```
Status code: 200
Content-Type: text/html; charset=UTF-8. 
```

**Details**
 - Phalcon version: ```5.0.0alpha7 (Micro)```
 - PHP Version: `8.0`
 - Operating System: `Ubuntu 20`
 - Installation type: `phalcon.so from the github archive`
 - Server: `Nginx/1.18.0 `
 
Also, if you reproduce the code below, the response status is set correctly:
```php
/* AccessMiddleware.php */
public function call(Phalcon\Mvc\Micro $app)
{
    $body = [ 'test' => 123 ];

    http_response_code(404);
    header('Content-Type: application/json; charset=UTF-8');
    
    // Tried $ this as well but no change 
    $app->response
        ->setJsonContent($body, JSON_NUMERIC_CHECK)
        ->send();
    exit();
}
```

Also tried changing the HTTP version to 2 and 1.1 - no result. 
Hope to find a solution to the problem :)

**Comment by destyk** [comment]
I would also like to note that I perform all actions on `Phalcon\Mvc\Micro`.

This problem is relevant when calling `$this->response->setStatusCode(code)` & `$this->response->setContentType()` methods in `$app->before()` event.

**Comment by niden** [comment]
@destyk Have a look below. I cannot reproduce this honestly.

The middleware is defined here:

https://github.com/niden/cphalcon/blob/T15836-response-code/tests/_data/fixtures/Micro/HttpResponseContentMiddleware.php

Note that it uses `$app->stop();` in the end instead of `exit()` as in your example

The test I am running is here:

https://github.com/niden/cphalcon/blob/T15836-response-code/tests/unit/Http/Response/GetSetStatusCodeCest.php#L181

which follows what you have. 

Thoughts?

**Comment by niden** [comment]
Since we released the code, could you please give it a try with 5.0.0beta1 and let us know?

**Comment by destyk** [comment]
@niden So now it has been updated to `Phalcon 5.0.0-beta1`.

Conducted the following experiment:
```php
/* app.php */
// ...
$app->before(
    new AccessMiddleware()
);
```

```php
/* AccessMiddleware.php */
public function call(Phalcon\Mvc\Micro $app)
{
    throw new \Exception('Error message', 404);
}
```

```php
/* app.php */
$app->error(function($e) use ($app) {
    $app->response
        ->setContentType('application/json', 'UTF-8')
        ->setStatusCode($e->getCode())
        ->setJsonContent([
            'code'    => $e->getCode(),
            'message' => $e->getMessage(),
        ])
        ->send();
});
```

I also tried this option:
```php
/* app.php */
$app->error(function($e) use ($app) {
    return $app->response
        ->setContentType('application/json', 'UTF-8')
        ->setStatusCode($e->getCode())
        ->setJsonContent([
            'code'    => $e->getCode(),
            'message' => $e->getMessage(),
        ]);
});
```

In the output, for some reason I still get status `200` and contentType `text/html; charset = UTF-8`. Tests were carried out on both HTTP 1/1 and HTTP 2

**Comment by niden** [comment]
@destyk Refreshing the links since we merged that code. This is the test I have - pretty much in line with your test case:

https://github.com/phalcon/cphalcon/blob/5.0.x/tests/unit/Http/Response/GetSetStatusCodeCest.php#L181

This is the middleware: 

https://github.com/phalcon/cphalcon/blob/5.0.x/tests/_data/fixtures/Micro/HttpResponseContentMiddleware.php

See what happens when you add 

`$app->stop()` after the `send()`

**Comment by destyk** [comment]
@niden I think I found where the mistake was. She's on my side.

My code:
```php
/* app.php */
// ...
$app->before(
    new CORSMiddleware()
);
$app->before(
    new AccessMiddleware()
);
```

```php
/* CORSMiddleware.php */
$app->response
    ->setHeader('Access-Control-Allow-Origin', '*')
    ->setHeader('Access-Control-Allow-Methods', 'POST, GET, PUT, OPTIONS, DELETE')
    ->setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Authorization, Accept, X-Accept-Charset, X-Accept, X-Temporary-Key')
    ->setHeader('Access-Control-Allow-Credentials', true)
    ->setHeader('Access-Control-Max-Age', 1000)
    ->sendHeaders(); // This needs to be removed 
```

The whole problem was that `CORSMiddleware.php` was the first to enter processing, which at the end of execution sent headers due to `sendHeaders()`. 

Now I removed `sendHeaders()` from `CORSMiddleware.php` and everything worked as expected. I apologize for my carelessness. Thank you for your help in finding the problem!

**Comment by niden** [comment]
@destyk Happy to hear you found the issue. One more positive, we added more tests to the framework :)

Thank you

Closing this.
