### ISSUE TITLE
[BUG]: Column::TYPE_BINARY and Column::TYPE_TINYINTEGER are both 26

### ISSUE THREAD

**Issue by jturbide** [phalcon/cphalcon#16532]
**Describe the bug**
Phalcon\Db\Column::TYPE_BINARY and Phalcon\Db\Column::TYPE_TINYINTEGER should not be equal

**To Reproduce**
```php
Column::TYPE_BINARY === Column::TYPE_TINYINTEGER // true
```

**Expected behavior**
```php
Column::TYPE_BINARY === Column::TYPE_TINYINTEGER // false
```

**Additional context**
Column::TYPE_BINARY is not numeric
Column::TYPE_TINYINTEGER is numeric
Missing unit test for TYPE_BINARY

**Comment by jturbide** [comment]
The biggest issue is when we are using casting (i.e. castOnHydrate) it will convert my binary into a int because it found the wrong type. Since I don't want to turn off casting on hydrate, and want to fix the bind type,  tis is my temporary solution for now. I made my own Mysql adapter to get around the issue affected by the wrong Column type value.

```php
use Phalcon\Db\Column;

class Mysql extends \Phalcon\Db\Adapter\Pdo\Mysql
{
    public function describeColumns(string $table, string $schema = null): array
    {
        $definitions = parent::describeColumns($table, $schema);
        
        if (Column::TYPE_TINYINTEGER !== Column::TYPE_BINARY) {
            return $definitions;
        }
        
        foreach ($definitions as $key => $definition) {
            
            if ($definition->getType() === Column::TYPE_TINYINTEGER && !$definition->isNumeric()) {
                // probably a binary at this point
                
                $newDefinition = [];
                
                // protected to public
                $prefix = chr(0).'*'.chr(0);
                foreach ((array)$definition as $key => $value) {
                    $newDefinition[str_replace($prefix, '', $key)] = $value;
                }
                
                $newDefinition['bindType'] = Column::BIND_PARAM_BLOB;
                $newDefinition['type'] = Column::TYPE_VARBINARY;
                unset($newDefinition['scale']);
                
                // reset definition
                $definitions[$key] = new Column($definition->getName(), $newDefinition);
            }
        }
        
        return $definitions;
    }
}
```

**Comment by niden** [comment]
This has been fixed in https://github.com/phalcon/cphalcon/pull/16562

Thank you @jturbide

**Comment by dunarri** [comment]
Hi, according to the release notes for version 5.7.0 this fix was included, however I've installed 5.7.0 and still have the issue.
Here is the code I used to reproduce it:
```
<?php
echo 'Using Phalcon '.phpversion('phalcon').PHP_EOL;

// Check column type values according to the original cause of issue 16532
use Phalcon\Db\Column;
var_dump(Column::TYPE_BINARY);
var_dump(Column::TYPE_TINYINTEGER);
var_dump(Column::TYPE_BINARY === Column::TYPE_TINYINTEGER);

class Test extends Phalcon\Mvc\Model
{
    public $id;
    public $binary_field;

    public function initialize()
    {
        $this->setSource('test');   // provide actual table name
    }
}

// Create a DI and setup the database connection
$di = new Phalcon\Di\FactoryDefault();
$di->setShared('db', function () {
    return new Phalcon\Db\Adapter\Pdo\Mysql([
        'host'     => 'localhost',
        'dbname'   => 'phalcon_binary_test',
        'username' => 'phalcon',
        'password' => 'secret',
    ]);
});
Phalcon\Di\Di::setDefault($di);

// Enable castOnHydrate
Phalcon\Mvc\Model::setup(['castOnHydrate' => true]);

$model = Test::findFirst(1);
var_dump($model->binary_field);
?>
```

And this is the result:
```
Using Phalcon 5.7.0
int(26)
int(26)
bool(true)
int(0)
```

I installed Phalcon from the remi repo using yum:
```
$ yum list installed | grep phalcon
php81-php-phalcon5.x86_64           5.7.0-1.el7.remi              @remi-safe    
```

**Comment by niden** [comment]
I am not sure about 5.7 but 5.8 has the correct code

https://github.com/phalcon/cphalcon/blob/5.0.x/phalcon/Db/Column.zep#L87
https://github.com/phalcon/cphalcon/blob/5.0.x/phalcon/Db/Column.zep#L202

**Comment by dunarri** [comment]
Should I install through PECL instead of yum and remi repo?

**Comment by niden** [comment]
You can give it a try. I am pretty sure that Remi already has v5.8 but in any case, give it a go with PECL and let us know
