### ISSUE TITLE
[BUG] Action forwarding is not working in 'dispatch:beforeException'.

### ISSUE THREAD

**Issue by temuri416** [phalcon/cphalcon#2851]
Hi all,

It is related to this: http://docs.phalconphp.com/en/latest/reference/dispatching.html#handling-not-found-exceptions. Whenever an exception is thrown, action forwarding to Error controller does not work and results in a blank page.

Steps to repro:
* Check out Phalcon's "INVO" example.
* Create ErrorController.php:
```php
    class ErrorController extends ControllerBase
    {
        public function indexAction()
        {
                error_log('Error Controller');
        }
    }
```
* Create view script "error/index.volt" with a message "KABOOM!"
* Edit /index.php and use the following code:
```php
	/**
	 * We register the events manager
	 */
	$di->set('dispatcher', function() use ($di) {

		$eventsManager = $di->getShared('eventsManager');
        $eventsManager->attach('dispatch:beforeDispatchLoop', function(Phalcon\Events\Event $event, Phalcon\Mvc\Dispatcher $dispatcher) {
            throw new \Exception('Just because');
        });

        $eventsManager->attach('dispatch:beforeException', function ($event, $dispatcher, $exception) use (&$di) {
            error_log('dispatch:beforeException');
            $dispatcher->forward(
                array(
                    'controller' => 'error',
                    'action'     => 'index',
                    'error' => $exception
                )
            );
            return false;
        });

		$security = new Security($di);

		/**
		 * We listen for events in the dispatcher using the Security plugin
		 */
		$eventsManager->attach('dispatch', $security);

		$dispatcher = new Phalcon\Mvc\Dispatcher();
		$dispatcher->setEventsManager($eventsManager);

		return $dispatcher;
	});
```

Exception "Just because" is thrown and caught in 'dispatch:beforeException'. However, forwarding to /error/index does not work. Execution terminates immediately after "return false". I am using PHPEd debugger to trace it.

Also,

Can Phalcon guys explain the following cryptic sentence from the docs:

```txt
Only exceptions produced by the dispatcher and exceptions produced in the executed action are notified in the ‘beforeException’ events. Exceptions produced in listeners or controller events are redirected to the latest try/catch.
```

What does that really mean?? 

Thanks!

**Comment by mikacalvo** [comment]
In the Invo app, if we print the NotFoundPlugin Exception caused by SecurityPlugin's beforeDispatch function, we get :
"Dispatcher has detected a cyclic routing causing stability problems"

Does that mean that we can't access the errors/show401 page ? Apparently, you forgot to declare it in the $publicResources array, but I did and the problem is still the same (same Exception, same message)

**Comment by temuri416** [comment]
@phalcon 

I've finally upgraded my project to the latest Phalcon 3.x.

The issue is still there. I was debugging INVO again, and whenever execution lands in `public function beforeException() ` action forwarding does not work. 

So, again - my question is as follows:

Can I expect the following code to forward action to ErrorsController:

```php
	public function beforeException(Event $event, MvcDispatcher $dispatcher, Exception $exception)
	{
		$dispatcher->forward(array(
			'controller' => 'errors',
			'action'     => 'show500'
		));
		return false;
	}
```

The way it works now - dispatcher exits the execution loop and action is not forwarded to ErrorsController.

**Comment by Jurigag** [comment]
I think this issue is already opened somewhere. @virgofx was planning to fix this.

**Comment by sergeyklay** [comment]
@temuri416 Did you try something like this

https://github.com/phalcon/phalcon-devtools/blob/3.0.x/scripts/Phalcon/Mvc/Dispatcher/ErrorHandler.php

**Comment by Jurigag** [comment]
But your code @sergeyklay won't work too. Check above.

**Comment by sergeyklay** [comment]
I checked it right now

**Comment by temuri416** [comment]
@sergeyklay 

Looking at that code I don't see any difference from what I pasted above. In both cases a boolean is returned.

Looking at `dispatcher.zip` I get a feeling that it's `this->_finished` that needs to be FALSE...

**Comment by Jurigag** [comment]
`beforeDispatchLoop` event is fired **OUTSIDE** of dispatch loop, this is why forward in beforeException can't happen.

**Comment by sergeyklay** [comment]
the problem is - how do you use it
https://github.com/phalcon/phalcon-devtools/blob/3.0.x/scripts/Phalcon/Access/Manager.php#L79-L86

**Comment by virgofx** [comment]
@temuri416 This is a problem. There is a more recent issue - https://github.com/phalcon/cphalcon/issues/11819

It's tentatively fixed and in a holding pattern waiting for a core bug in Zephir to be fixed before it will be merged. Hopefully very soon

**Comment by virgofx** [comment]
This can be closed and marked as duplicate.

**Comment by Jurigag** [comment]
@virgofx 

You mean this issue i created - https://github.com/phalcon/zephir/issues/1336 ? I guess it's possibly affecting code like:

```
try {

}
catch {
try {

}
catch {

}
}
```

too

**Comment by Jurigag** [comment]
Anyway this problem form this issue actually is not related to those issues - just current code is not allowing to forward from beforeDispatchLoop or afterDispatchLoop, no bug or something. Just forward can be done only from dispatch loop, obviously before or after it you can't do it.

**Comment by virgofx** [comment]
Yes and that's all fixed here :)
https://github.com/virgofx/cphalcon/blob/b3eaeda7e09d3b57df6fd3781b09afe1a91db458/tests/unit/Mvc/Dispatcher/DispatcherBeforeDispatchLoopTest.php#L98

**Comment by Jurigag** [comment]
Actually not fixed, just nowe feature to forward from beforeDispatchLoop and afterDispatchLoop

also update tests @virgofx because i latest checked tests are failing in your repo with those changes

**Comment by virgofx** [comment]
Will check juri. Last I ran, everything was working, 100% on the dispatcher was working. The old dispatcher tests were removed because they're weren't accurate.

**Comment by Jurigag** [comment]
Oh then it's possible i run tests in wrong repo then.... my mistake if i did this

**Comment by temuri416** [comment]
@virgofx 

Thanks. Is there an ETA on a bugfix for this?

**Comment by temuri416** [comment]
Hi all,

I've looked closely at the execution workflow and quite honestly, don't see how to fix this without refactoring dispatch method.

The only thing that comes to mind is to enclose every event fire in its own try / catch block similar to [https://github.com/phalcon/cphalcon/blob/master/phalcon/dispatcher.zep#L341](url).

Is this the intended approach?

Thanks!

**Comment by Jurigag** [comment]
Do you understand there is NO BUG ? Forward can happen only from DISPATCH LOOP, like from WHILE, you currently trying to forward outside of dispatch loop which obviously don't work. This is not bug, this is NFR, create seperated issue.

**Comment by temuri416** [comment]
Yes, I see this is not a bug.

> Forward can happen only from DISPATCH LOOP.

Yes, right now that's the way it is. But there's no reason it could not happen from anywhere inside https://github.com/phalcon/cphalcon/blob/master/phalcon/dispatcher.zep#L390 loop.

**Comment by Jurigag** [comment]
But doing forward from event works fine. The problem which there is is throwing exception from event - this doesn't work currently and we are talking mostly about this with @virgofx Forward should work totally fine, i even using it extensively and there are no any problem.
