### ISSUE TITLE
[2.0] Mvc\Router\Group doesn't take array as path

### ISSUE THREAD

**Issue by RickyGit** [phalcon/cphalcon#3306]
With Mvc\Router, path can be declarated with array : 
```php
$this->add('/test', [
    'module' => 'frontoffice',
    'controller' => 'index',
    'action' => 'index'
]);
```
or with string : 
```php
$this->add('/test', 'frontoffice::index::index');
```

But **it's not possible in Mvc\Router\Group (it's in 1.3.4).**

Cause is https://github.com/phalcon/cphalcon/blob/2.0.0/phalcon/mvc/router/group.zep#L218
If paths is string, we create a route with default paths, without take paths.

A possible fix is to copy this code https://github.com/phalcon/cphalcon/blob/2.0.0/phalcon/mvc/router/route.zep#L311-L370 into the _addRoute method of Routeur\Group.

But, maybe there is simpler ?

**Comment by andresgutierrez** [comment]
Fixed in Phalcon 2.0.1

**Comment by RickyGit** [comment]
Sorry but it's not fixed.

Test with Phalcon 2.0.3.

This code works : 
```php
class Routeur extends \Phalcon\Mvc\Router\Group
{
	public function initialize()
	{
		$this->add('/test', [
  			'module' => 'frontoffice',
   			'controller' => 'index',
   			'action' => 'index'
		]);
	}
}
```


This code doesn't : 
```php
class Routeur extends \Phalcon\Mvc\Router\Group
{
	public function initialize()
	{
		$this->add('/test', 'frontoffice::index::index');
	}
}
```

It's OK with \Phalcon\Mvc\Router, but not with \Phalcon\Mvc\Router\\**Group**

**Comment by andresgutierrez** [comment]
@RickyGit It's defined as "var paths" everywhere:

* https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/router/group.zep#L76
* https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/router/group.zep#L147
* https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/router/group.zep#L176
* https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/router/group.zep#L188
* https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/router/group.zep#L200
* https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/router/group.zep#L212
* https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/router/group.zep#L224

**Comment by RickyGit** [comment]
Yes but the problem is here : 
https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/router/group.zep#L291
If path is not an array, mergedPaths = defaultPaths ==> var paths is ignored.

Whereas, in route : 
https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/router/route.zep#L344-L370

**Comment by andresgutierrez** [comment]
Routes aren't processed there because they are passed in the constructor of Route: https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/router/group.zep#L176

**Comment by andresgutierrez** [comment]
I've added a fix to support string paths

**Comment by RickyGit** [comment]
Thanks! It works.
